### ISSUE TITLE
follower broken in fuerte

### ISSUE THREAD

**Issue by LucidOne** [turtlebot/turtlebot_apps#18]
Not sure why, yet.

**Comment by jihoonl** [comment]
namespacing in 3dsensor.launch is a little mess. I am testing now. I will update this issue when things are cleared.

**Comment by jihoonl** [comment]
I confirmed that 3dsensor.launch does not stream pointcloud properly now. Will be fixed in a couple of days. 
For immediate use, modify turtlebot_follower/app/follwer.launch

 remove <include file="$(find turtlebot_bringup)/launch/3dsensor.launch" />

and add
 <include file="$(find openni_launch)/launch/openni.launch" />

**Comment by jihoonl** [comment]
Got it working. check out the lastest version.

**Comment by stonier** [comment]
But moving on to groovy...
