### ISSUE TITLE
DepthImage_to_LaserScan

### ISSUE THREAD

**Issue by stonier** [turtlebot/turtlebot_apps#20]
Replace pointcloud_to_laserscan with this. Should be much more lightweight.
- Use the camera_driver nodelet only
- Run this on top

i.e. no PCL.

The source

> https://github.com/ros-perception/depthimage_to_laserscan

Chad Rockey is the guy to email with questions.

> chadrockey@willowgarage.com

**Comment by corot** [comment]
I gave a try to DepthImage_to_LaserScan and works fine. But it isn't still a deb package, so we will wait a little bit

**Comment by corot** [comment]
Released as deb package. It's working but many times makes camera_nodelet_manager crash. I'll try how much performance we loss running it in a separated node.

**Comment by chadrockey** [comment]
What's the message when the nodelet manager crashes?

**Comment by chadrockey** [comment]
This pull requested launch file works for me under the latest groovy:
https://github.com/turtlebot/turtlebot/pull/38

If that pull request is accepted, then the apps that used to launch pcl_to_laserscan or _pcl_to_laserscan should be updated.

**Comment by chadrockey** [comment]
I forgot to mention that I tested under the latest Groovy beta release on Ubuntu 12.04 64 bit.

What environment are you testing?  I'll see if I can duplicate the issue.

**Comment by corot** [comment]
The new launch file is working fine. We are updating our apps to use it

**Comment by corot** [comment]
Check how good/bad it is.... sometimes turtlebot looks like blind

**Comment by chadrockey** [comment]
If it's missing obstacles, you should check the "scan_height" parameter.  It defaults to 1 pixel which is a very narrow laser plane.  The old behavior was probably equivalent to something like 10-20 pixels.  It should be available through dynamic_reconfigure (once reconfigure_gui is working @zklapow).

CPU usage will be proportional to scan_height, since it controls how many pixels are merged into the final scan.

More information on the wiki page:
http://www.ros.org/wiki/depthimage_to_laserscan

**Comment by corot** [comment]
Thank you very much for your help (and for this package!).
Caught it. It's mostly intended for navigation, as the old good narrow scan, right? I'll keep around 10 pixels.
