### ISSUE TITLE
Panorama app not working: robot spins forever

### ISSUE THREAD

**Issue by corot** [turtlebot/turtlebot_apps#54]
at least when using it with android frontend

Also the pano image keeps our beloved smurfs color scheme (R and B flipped, if I remember properly)

**Comment by stonier** [comment]
@yhju talk to marcus about these issues. Are they the same as in groovy? Is the R&B problem new?

**Comment by yhju** [comment]
**Root Cause:**

[`cv_bridge`](http://www.ros.org/wiki/cv_bridge) provides color conversion logic between `cv::IplImage` and `sensor_msgs::Image`. But some supported color conversions are obsoluted from the **groovy** distro. 
- [evidence](https://github.com/ros-perception/vision_opencv/blob/groovy-devel/cv_bridge/src/cv_bridge.cpp#L119)

Take a look `getFormat` function of `cv_bridge` pacakge between **groovy-devel** and **fuerte-devel** branches for more detail:
- [`fuerte-devel`](https://github.com/ros-perception/vision_opencv/blob/fuerte-devel/cv_bridge/src/cv_bridge.cpp#L102)
- [`groovy-devel`](https://github.com/ros-perception/vision_opencv/blob/groovy-devel/cv_bridge/src/cv_bridge.cpp#L105)

---

**Caused Problem:**

`turtlebot_panorama` app uses `capture_server.py` to do image capturing and stitching. When it [publish final stitched image](https://github.com/turtlebot/turtlebot_apps/blob/d3de7ca84d8113ad0e231be6a9c7a4aae4377b0d/software/pano/pano_ros/nodes/capture_server.py#L344) via `panorama` topic, its default encoding is `CV_8UC3`. Theoretically, it can be converted to either `rgb8` or `bgr8`. **fuerte** version of `cv_bridge` convert it to `rgb8` explicitly. But **groovy** just throw it away by raising [an exception](https://github.com/ros-perception/vision_opencv/blob/groovy-devel/cv_bridge/src/cv_bridge.cpp#L205).

In my setup(hydro), `image_view` failed to showing stitched image, and it only shows single snapshots of progress.

---

**Conclusion:**

By setting its encoding explicitly to `rgb8`,  resolved this issue both on android panorama app and `image_view`. - d3de7ca84d8113ad0e231be6a9c7a4aae4377b0d

I have no idea on android app, but flipped image problem seems to be related to the fact that default color(channel) order of opencv(IplImage) is BGR.

**Comment by corot** [comment]
woah!!!!  cool analysis of a problem/solution!
